name: ai-sales-insight
services:
- dockerfile_path: backend/Dockerfile.prod
  github:
    branch: main
    deploy_on_push: true
    repo: utkarshhmishra/AI-Sales-Insight
  health_check:
    http_path: /api/v1/health
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: backend
  routes:
  - path: /api
  source_dir: /
- build_command: npm install && npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: utkarshhmishra/AI-Sales-Insight
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: frontend
  routes:
  - path: /
  run_command: npx serve -s dist -l 3000
  source_dir: frontend
